'use strict';

const ACTIONS = ['apply', 'donate_currency', 'leave']; const ASCII = /^[\x21-\x7E]+$/; const $ = id => document.getElementById(id);
const form = $('guildForm'); const prefix = $('prefix'); const count = $('count'); const password = $('password'); const concurrency = $('concurrency'); const accessCode = $('accessCode'); const resultBody = $('resultBody'); const startButton = $('startButton'); const stopButton = $('stopButton'); const retryButton = $('retryButton'); const toast = $('toast');
let accounts = []; let selectedActions = []; let running = false; let controller; let toastTimer;
const newStage = () => ({ state: 'pending', text: '等待', detail: '' }); const newAccount = (username, index) => ({ username, index, token: '', login: newStage(), apply: newStage(), donate_currency: newStage(), leave: newStage(), result: 'pending', finished: false });
function showToast(message) { clearTimeout(toastTimer); toast.textContent = message; toast.classList.add('show'); toastTimer = setTimeout(() => toast.classList.remove('show'), 2600); }
function escapeHtml(value) { return String(value).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]); }
function stageHtml(item) { return `<span class="status status-${item.state}" title="${escapeHtml(item.detail)}">${escapeHtml(item.text)}</span>`; }
function resultHtml(item) { const state = item.result === 'success' ? 'success' : item.result === 'running' ? 'running' : 'error'; return `<span class="result-pill result-${state}">${item.result === 'success' ? '全部成功' : item.result === 'running' ? '处理中' : item.result === 'stopped' ? '已停止' : item.result === 'pending' ? '等待' : '有失败项'}</span>`; }
function render() { resultBody.innerHTML = accounts.map(item => `<tr id="account-${item.index}"><td>${String(item.index).padStart(2, '0')}</td><td><span class="account-name">${escapeHtml(item.username)}</span></td><td data-cell="login">${stageHtml(item.login)}</td><td data-cell="apply">${stageHtml(item.apply)}</td><td data-cell="donate_currency">${stageHtml(item.donate_currency)}</td><td data-cell="leave">${stageHtml(item.leave)}</td><td data-cell="result">${resultHtml(item)}</td></tr>`).join(''); updateStats(); }
function renderAccount(item) { const row = $(`account-${item.index}`); if (!row) return; [...ACTIONS, 'login'].forEach(key => { row.querySelector(`[data-cell="${key}"]`).innerHTML = stageHtml(item[key]); }); row.querySelector('[data-cell="result"]').innerHTML = resultHtml(item); updateStats(); }
function updateStats() { const done = accounts.filter(item => item.finished).length; $('completedCount').textContent = done; $('totalCount').textContent = accounts.length; $('successCount').textContent = accounts.filter(item => item.result === 'success').length; $('failureCount').textContent = accounts.filter(item => item.finished && item.result !== 'success').length; $('progressBar').style.width = accounts.length ? `${done / accounts.length * 100}%` : '0%'; }
function setStage(item, state, text, detail = '') { Object.assign(item, { state, text, detail }); }
function operationId() { const values = new Uint32Array(2); crypto.getRandomValues(values); return `guild_action_${Date.now().toString(36)}_${Array.from(values, value => value.toString(36)).join('')}`; }
async function request(payload, signal) { const response = await fetch('/api/guild/action', { method: 'POST', headers: { 'Content-Type': 'application/json', Accept: 'application/json' }, body: JSON.stringify(payload), cache: 'no-store', signal }); const raw = await response.text(); let data; try { data = raw ? JSON.parse(raw) : {}; } catch { throw new Error(`服务器返回了非 JSON 内容（HTTP ${response.status}）`); } if (!response.ok || !data.ok) throw new Error(data.msg || `请求失败（HTTP ${response.status}）`); return data; }
async function processAccount(item, signal) {
  item.finished = false; item.result = 'running';
  try { if (item.login.state !== 'success') { setStage(item.login, 'running', '登录中'); renderAccount(item); const result = await fetch('/api/login', { method: 'POST', headers: { 'Content-Type': 'application/json', Accept: 'application/json' }, body: JSON.stringify({ username: item.username, password: password.value }), cache: 'no-store', signal }).then(async response => { const data = await response.json(); if (!response.ok || !data.ok) throw new Error(data.msg || `登录失败（HTTP ${response.status}）`); return data; }); item.token = result.token; setStage(item.login, 'success', '登录成功'); } }
  catch (error) { setStage(item.login, signal.aborted ? 'pending' : 'error', signal.aborted ? '已停止' : '登录失败', error.message); item.result = signal.aborted ? 'stopped' : 'error'; item.finished = true; renderAccount(item); return; }
  for (const action of selectedActions) { if (signal.aborted) break; const current = item[action]; if (current.state === 'success') continue; setStage(current, 'running', action === 'apply' ? '进会中' : action === 'donate_currency' ? '捐赠中' : '退会中'); renderAccount(item); try { const payload = action === 'apply' ? { token: item.token, action: 'apply', guild_id: 4, operation_id: operationId() } : action === 'donate_currency' ? { token: item.token, action: 'donate_currency', currency: 'gems', amount: 38800, operation_id: operationId() } : { token: item.token, action: 'leave', operation_id: operationId() }; const result = await request(payload, signal); setStage(current, 'success', '成功', result.msg || '执行成功'); } catch (error) { setStage(current, signal.aborted ? 'pending' : 'error', signal.aborted ? '已停止' : '失败', error.message); } renderAccount(item); }
  item.finished = true; item.result = selectedActions.every(action => item[action].state === 'success') ? 'success' : signal.aborted ? 'stopped' : 'error'; renderAccount(item);
}
async function run(targets) { controller = new AbortController(); running = true; startButton.disabled = true; stopButton.hidden = false; retryButton.disabled = true; $('runStatus').textContent = '正在执行'; const queue = [...targets]; const workers = Array.from({ length: Math.min(Number(concurrency.value), queue.length) }, async () => { while (queue.length && !controller.signal.aborted) await processAccount(queue.shift(), controller.signal); }); await Promise.all(workers); queue.forEach(item => { item.finished = true; item.result = 'stopped'; renderAccount(item); }); running = false; startButton.disabled = false; stopButton.hidden = true; retryButton.disabled = !accounts.some(item => item.result !== 'success'); $('runStatus').textContent = controller.signal.aborted ? '已停止' : '执行完成'; showToast(controller.signal.aborted ? '任务已停止' : '批量执行完成'); }
function validAccess() { if (accessCode.value.trim().toUpperCase() === getDailyAccessCode()) return true; showToast('每日访问密码错误'); accessCode.focus(); return false; }
function setInputs(disabled) { [prefix, count, password, concurrency, accessCode].forEach(input => { input.disabled = disabled; }); document.querySelectorAll('input[name="action"]').forEach(input => { input.disabled = disabled; }); }
prefix.addEventListener('input', () => { const value = prefix.value.trim() || 'account'; $('namePreview').textContent = `将处理 ${value}1、${value}2、${value}3…`; });
form.addEventListener('submit', event => { event.preventDefault(); if (running || !form.reportValidity() || !validAccess()) return; const name = prefix.value.trim(); const total = Number(count.value); if (!Number.isInteger(total) || total < 1 || total > 500) return showToast('账号数量需要在 1 到 500 之间'); if (!ASCII.test(name) || !ASCII.test(password.value) || password.value.length < 6 || password.value.length > 32) return showToast('账号开头和密码只能使用可见 ASCII 字符'); selectedActions = [...document.querySelectorAll('input[name="action"]:checked')].map(input => input.value); if (!selectedActions.length) return showToast('至少选择一项动作'); const usernames = Array.from({ length: total }, (_, index) => `${name}${index + 1}`); const invalid = usernames.find(item => item.length < 6 || item.length > 20); if (invalid) return showToast(`生成的账号 ${invalid} 不符合 6–20 位要求`); accounts = usernames.map((item, index) => newAccount(item, index + 1)); render(); setInputs(true); $('resultsPanel').scrollIntoView({ behavior: 'smooth' }); run(accounts).finally(() => setInputs(false)); });
stopButton.addEventListener('click', () => { if (controller && running) { stopButton.disabled = true; controller.abort(); $('runStatus').textContent = '正在停止'; } });
retryButton.addEventListener('click', () => { if (!validAccess()) return; const targets = accounts.filter(item => item.result !== 'success'); targets.forEach(item => { item.finished = false; item.result = 'pending'; ['login', ...selectedActions].forEach(key => { if (item[key].state === 'error') setStage(item[key], 'pending', '等待重试'); }); renderAccount(item); }); setInputs(true); run(targets).finally(() => setInputs(false)); });
updateStats();
