'use strict';

const API_BASE = '/api';
const REWARDS = { daily: '每日金刚石', 'gift-1': 'VIP1 奖励', 'gift-2': 'VIP2 奖励' };
const ASCII = /^[\x21-\x7E]+$/;
const $ = id => document.getElementById(id);
const form = $('vipForm'); const prefix = $('prefix'); const count = $('count'); const password = $('password'); const concurrency = $('concurrency'); const accessCode = $('accessCode'); const resultBody = $('resultBody'); const startButton = $('startButton'); const stopButton = $('stopButton'); const retryButton = $('retryButton'); const toast = $('toast');
let accounts = []; let running = false; let controller; let toastTimer; let selectedRewards = [];
const newStage = () => ({ state: 'pending', text: '等待', detail: '' });
const newAccount = (username, index) => ({ username, index, token: '', login: newStage(), exchange: newStage(), rewards: Object.fromEntries(Object.keys(REWARDS).map(key => [key, newStage()])), result: 'pending', finished: false });
function showToast(message) { clearTimeout(toastTimer); toast.textContent = message; toast.classList.add('show'); toastTimer = setTimeout(() => toast.classList.remove('show'), 2600); }
function escapeHtml(value) { return String(value).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]); }
function stageHtml(item) { return `<span class="status status-${item.state}" title="${escapeHtml(item.detail)}">${escapeHtml(item.text)}</span>`; }
function resultHtml(item) { const state = item.result === 'success' ? 'success' : item.result === 'running' ? 'running' : 'error'; return `<span class="result-pill result-${state}">${item.result === 'success' ? '全部成功' : item.result === 'running' ? '处理中' : item.result === 'stopped' ? '已停止' : item.result === 'pending' ? '等待' : '有失败项'}</span>`; }
function render() { resultBody.innerHTML = accounts.map(item => `<tr id="account-${item.index}"><td>${String(item.index).padStart(2, '0')}</td><td><span class="account-name">${escapeHtml(item.username)}</span></td><td data-cell="login">${stageHtml(item.login)}</td><td data-cell="exchange">${stageHtml(item.exchange)}</td>${Object.keys(REWARDS).map(key => `<td data-cell="${key}">${stageHtml(item.rewards[key])}</td>`).join('')}<td data-cell="result">${resultHtml(item)}</td></tr>`).join(''); updateStats(); }
function renderAccount(item) { const row = $(`account-${item.index}`); if (!row) return; ['login', 'exchange'].forEach(key => { row.querySelector(`[data-cell="${key}"]`).innerHTML = stageHtml(item[key]); }); Object.keys(REWARDS).forEach(key => { row.querySelector(`[data-cell="${key}"]`).innerHTML = stageHtml(item.rewards[key]); }); row.querySelector('[data-cell="result"]').innerHTML = resultHtml(item); updateStats(); }
function updateStats() { const done = accounts.filter(item => item.finished).length; $('completedCount').textContent = done; $('totalCount').textContent = accounts.length; $('successCount').textContent = accounts.filter(item => item.result === 'success').length; $('failureCount').textContent = accounts.filter(item => item.finished && item.result !== 'success').length; $('progressBar').style.width = accounts.length ? `${done / accounts.length * 100}%` : '0%'; }
function setStage(item, state, text, detail = '') { Object.assign(item, { state, text, detail }); }
function operationId(prefix) { return `${prefix}_${Date.now().toString(36)}_${crypto.randomUUID().replaceAll('-', '').slice(0, 12)}`; }
async function request(path, payload, signal) { const response = await fetch(`${API_BASE}${path}`, { method: 'POST', headers: { 'Content-Type': 'application/json', Accept: 'application/json' }, body: JSON.stringify(payload), cache: 'no-store', signal }); const raw = await response.text(); let data; try { data = raw ? JSON.parse(raw) : {}; } catch { throw new Error(`服务器返回了非 JSON 内容（HTTP ${response.status}）`); } if (!response.ok || !data.ok) throw new Error(data.msg || `请求失败（HTTP ${response.status}）`); return data; }
async function processAccount(item, signal) {
  item.finished = false; item.result = 'running';
  try { if (item.login.state !== 'success') { setStage(item.login, 'running', '登录中'); renderAccount(item); const result = await request('/login', { username: item.username, password: password.value }, signal); item.token = result.token; setStage(item.login, 'success', '登录成功'); } if (selectedRewards.includes('exchange') && item.exchange.state !== 'success') { setStage(item.exchange, 'running', '开通中'); renderAccount(item); const result = await request('/vip/exchange', { token: item.token, yuanbao_amount: 10000, operation_id: operationId('vip_exchange') }, signal); setStage(item.exchange, 'success', '开通成功', result.msg || '开通成功'); } else if (!selectedRewards.includes('exchange')) { setStage(item.exchange, 'pending', '未选择'); } }
  catch (error) { const current = item.login.state === 'running' ? item.login : item.exchange; setStage(current, signal.aborted ? 'pending' : 'error', signal.aborted ? '已停止' : `${current === item.login ? '登录' : '开通'}失败`, error.message); item.result = signal.aborted ? 'stopped' : 'error'; item.finished = true; renderAccount(item); return; }
  for (const key of selectedRewards.filter(item => item !== 'exchange')) { if (signal.aborted) break; const current = item.rewards[key]; if (current.state === 'success') continue; setStage(current, 'running', '领取中'); renderAccount(item); try { const payload = key === 'daily' ? { token: item.token, operation_id: operationId('vip_claim_daily') } : { token: item.token, level: Number(key.slice(-1)), operation_id: operationId('vip_claim_gift') }; const result = await request(key === 'daily' ? '/vip/claim-daily' : '/vip/claim-gift', payload, signal); setStage(current, 'success', '成功', result.msg || '领取成功'); } catch (error) { setStage(current, signal.aborted ? 'pending' : 'error', signal.aborted ? '已停止' : '失败', error.message); } renderAccount(item); }
  item.finished = true; item.result = selectedRewards.filter(key => key !== 'exchange').every(key => item.rewards[key].state === 'success') && (!selectedRewards.includes('exchange') || item.exchange.state === 'success') ? 'success' : signal.aborted ? 'stopped' : 'error'; renderAccount(item);
}
async function run(targets) { controller = new AbortController(); running = true; startButton.disabled = true; stopButton.hidden = false; retryButton.disabled = true; $('runStatus').textContent = '正在执行'; const queue = [...targets]; const workers = Array.from({ length: Math.min(Number(concurrency.value), queue.length) }, async () => { while (queue.length && !controller.signal.aborted) await processAccount(queue.shift(), controller.signal); }); await Promise.all(workers); queue.forEach(item => { item.finished = true; item.result = 'stopped'; renderAccount(item); }); running = false; startButton.disabled = false; stopButton.hidden = true; retryButton.disabled = !accounts.some(item => item.result !== 'success'); $('runStatus').textContent = controller.signal.aborted ? '已停止' : '执行完成'; showToast(controller.signal.aborted ? '任务已停止' : 'VIP 批量任务完成'); }
function validAccess() { if (accessCode.value.trim().toUpperCase() === getDailyAccessCode()) return true; showToast('每日访问密码错误'); accessCode.focus(); return false; }
function setInputs(disabled) { [prefix, count, password, concurrency, accessCode].forEach(input => { input.disabled = disabled; }); document.querySelectorAll('input[name="reward"]').forEach(input => { input.disabled = disabled; }); }
prefix.addEventListener('input', () => { const value = prefix.value.trim() || 'account'; $('namePreview').textContent = `将处理 ${value}1、${value}2、${value}3…`; });
form.addEventListener('submit', event => { event.preventDefault(); if (running || !form.reportValidity() || !validAccess()) return; const name = prefix.value.trim(); const total = Number(count.value); if (!Number.isInteger(total) || total < 1 || total > 500) return showToast('账号数量需要在 1 到 500 之间'); if (!ASCII.test(name) || !ASCII.test(password.value) || password.value.length < 6 || password.value.length > 32) return showToast('账号开头和密码只能使用可见 ASCII 字符'); selectedRewards = [...document.querySelectorAll('input[name="reward"]:checked')].map(input => input.value); if (!selectedRewards.length) return showToast('至少选择一项奖励'); const usernames = Array.from({ length: total }, (_, index) => `${name}${index + 1}`); const invalid = usernames.find(item => item.length < 6 || item.length > 20); if (invalid) return showToast(`生成的账号 ${invalid} 不符合 6–20 位要求`); accounts = usernames.map((item, index) => newAccount(item, index + 1)); render(); setInputs(true); $('resultsPanel').scrollIntoView({ behavior: 'smooth' }); run(accounts).finally(() => setInputs(false)); });
stopButton.addEventListener('click', () => { if (controller && running) { stopButton.disabled = true; controller.abort(); $('runStatus').textContent = '正在停止'; } });
retryButton.addEventListener('click', () => { if (!validAccess()) return; const targets = accounts.filter(item => item.result !== 'success'); targets.forEach(item => { item.finished = false; item.result = 'pending'; ['login', 'exchange'].forEach(key => { if (item[key].state === 'error') setStage(item[key], 'pending', '等待重试'); }); selectedRewards.filter(key => key !== 'exchange').forEach(key => { if (item.rewards[key].state === 'error') setStage(item.rewards[key], 'pending', '等待重试'); }); renderAccount(item); }); setInputs(true); run(targets).finally(() => setInputs(false)); });
updateStats();
